heat_template_version: 2015-04-30

description: Animbus OpenStack deployment group template.

parameters:
  image:
    type: string
    description: OpenStack deploy image.
    default: animbus_base_os
    constraints:
    - custom_constraint: glance.image
      description: >
        Name or ID of Image for Animbus 4.0GA deploy.

  flavor:
    type: string
    description: OpenStack deploy flavor.
    default: 2C_6G_60GB
    constraints:
    - custom_constraint: nova.flavor
      description: >
        Name or ID of Image for Animbus 4.0GA deploy.

  os_pub_net:
    type: string
    description: OpenStack public network.
    default: dev-net-214
    constraints:
    - custom_constraint: neutron.network
      description: >
        Name or ID of Image for Animbus 4.0GA deploy.

  os_int_net:
    type: string
    description: OpenStack internal network for vxlan.
    default: k-net
    constraints:
    - custom_constraint: neutron.network
      description: >
        Name or ID of Image for Animbus 4.0GA deploy. 
   
  os_volume_size:
     type: number
     description: OpenStack instance volume size.
     default: 60
 
  num_instances:
    type: number
    description: OpenStack instance numbers.
    default: 5
 
  admin_user:
    type: string
    description: OpenStack instance root user.
    default: root
 
  admin_passwd:
    type: string
    description: OpenStack instance root user.
    default: openstack
 
  instance_name:
    type: string
    description: OpenStack instance name.
    default: os_node
 
  volume_name:
    type: string
    description: OpenStack instance volume name.
    default: os_volume
 
resources:
  instance_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: num_instances }
      resource_def:
        type: preprare_deploy_env.yaml
        properties:
          instance_name: os_node_%index%
          volume_name: os_volume_%index%
          image: { get_param: image }
          flavor: { get_param: flavor }
          os_pub_net: { get_param: os_pub_net }
          os_int_net: { get_param: os_int_net }
          os_volume_size: { get_param: os_volume_size }
          admin_user: { get_param: admin_user }
          admin_passwd: { get_param: admin_passwd }

outputs:
  instance_output:
    value: { get_attr: [instance_group, show] }
